variables:
  repositoryWebNavigator: 'jannemattila/web-navigator'
  repositoryWebNavigatorStats: 'jannemattila/web-navigator-stats'

trigger:
- main
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repositoryWebNavigator)
        command: 'buildAndPush'
        Dockerfile: "src/WebNavigator/Dockerfile"
        buildContext:
        tags: |
          $(Build.BuildNumber)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repositoryWebNavigatorStats)
        command: 'buildAndPush'
        Dockerfile: "src/WebNavigatorStatistics/Dockerfile"
        buildContext:
        tags: |
          $(Build.BuildNumber)
          latest

