variables:
  repository: 'jannemattila/web-navigator'

trigger:
- main
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: 'src/WebNavigator/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest    
